# Generated by Django 5.0.4 on 2024-04-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categorymptt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorymptt',
            table='categorymptt',
        ),
    ]
